version: "3.9"
services:
  backend:
    build: ./backend
    container_name: backend
    environment:
      MONGODB_CONNECTION_STRING: "mongodb://mongodb:27017"
      PORT: 3000
      REDIS_URL: redis://redis:6379
      DB_NAME: todo
    ports:
      - 3000:3000
    volumes:
      - ./backend:/usr/src/app/backend
      - /usr/src/app/backend/node_modules
    working_dir: /usr/src/app/backend
    command: ["nodemon", "--legacy-watch", "app.js"]
    depends_on:
      - mongodb
      - redis
  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - 27017:27017
    restart: always
    volumes:
      - mongodb:/data/db
  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    restart: always
volumes:
  mongodb:
